### PR TITLE
My pull request

### PR DESCRIPTION
**Pull request by coltonehrman**
:100: 
:+1:

### CODE REVIEW

**Comment by btholt** [comment]
The first of many commits to come! :octocat:

**Comment by coltonehrman** [comment]
Hey Brian. I watched you and Nina's Intro to Web Development on Front End Masters. I just want to say that it was a great course and I learned a lot from it! Also, would it be possible if you could help me get started on finding small projects that I could maybe contribute to, and how to go about contributing? Thanks

**Comment by btholt** [comment]
Thank you! Glad you enjoyed it!

As far as your question, it's always a difficult to answer (and one people who are starting out frequently ask.) The best answer anyone ever gave me is contribute to things you already use. People want to jump in and start contributing to Rails, Django, Angular, etc. right away but it's easier to just start using something. When you use something, you're bound to run into bugs and corner cases that the code breaks. That's where it's best to start contributing: something you're already using and have some familiarity with it. Even if you just file an issue about the bug, that's still contributing, hence why filing an issue counts as a contribution on your contribution graph on your profile.

Does that rambling make sense? My first contribution (or one of the first anyway) was when I found a bug on the accordion in Bootstrap and I opened a PR to fix it. Ended up getting rejected but it kind of got me hooked on open source! Keep at it! It's fun!

Also, hanging out in Gitter / #Freenode chat channels of your favorite projects is a good way to pick up bugs / documentation fixes to do too.

**Comment by coltonehrman** [comment]
Yes! Definitely makes sense! Thanks for all the good information :) One last question. So, I am trying to start a career as a web developer right, but I find the front-end/design work kind of challenging because I am not very creative and it takes me forever to put together a design that I like and it's just very frustrating... Are most front-end developer jobs where you have to come up with the design and everything yourself? Or is it possible to find a job where you are giving a clear picture of how the client wants the website to look and work?

**Comment by btholt** [comment]
I've only done a handful of freelance jobs so my opinion on how to work freelance is very limited in its usefulness. However I have very little design ability. I can throw together a page that's useful but my ability to create a new design from nothing is not good. The few times I have ventured out in freelance I've always hired a designer I like and then just passed the bill onto the client or I've told the client to go his/her own designs and bring them to me.

I would definitely assert that a significant portion of front-end devs are in the same boat as you and me: their design skills are dubious at best so you're in good company. I've read parts of [Design for Hackers](http://www.amazon.com/Design-Hackers-Reverse-Engineering-Beauty/dp/1119998956) and that did give me some insight on how to at least understand some basics of design.

**Pull request merged**
